export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'

export const SET_SUGGESTS_POPUP_PROPS = 'SET_SUGGESTS_POPUP_PROPS'

export const SHOW_BOOK_POPUP = 'SHOW_BOOK_POPUP'
export const HIDE_BOOK_POPUP = 'HIDE_BOOK_POPUP'

export const FETCH_SUGGESTS_LOADING = 'FETCH_SUGGESTS_LOADING'
export const FETCH_SUGGESTS_SUCCESS = 'FETCH_SUGGESTS_SUCCESS'
export const FETCH_SUGGESTS_ERROR = 'FETCH_SUGGESTS_ERROR'

export const FETCH_BOOKS_LOADING = 'FETCH_BOOKS_LOADING'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'
export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR'
