export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
export const FETCH_SUGGESTS_LOADING = 'FETCH_SUGGESTS_LOADING'
export const FETCH_SUGGESTS_SUCCESS = 'FETCH_SUGGESTS_SUCCESS'
export const FETCH_SUGGESTS_ERROR = 'FETCH_SUGGESTS_ERROR'
